server:
  port: 8080

app:
  domain:
    default-max-age: 3600
    paths:
      base: "/experience/"
      query-handler: "/api"
    allowed-origins:
      - "*"
    allowed-headers:
      - "X-COMP-ERROR-X"
  swagger:
    name: "test"
    desc: "Microservice"
    contacto:
      name: "Andres Hippie"
      url: "127.0.0.1"
      email: "andreshincapie82132@gmail.com"
    license: "Apache 2.0"
    license-url: "https://www.apache.org/licenses/LICENSE-2.0.html"

spring:
  datasource:
    url: jdbc:postgresql://ec2-54-161-58-21.compute-1.amazonaws.com:5432/d5lve0v6ulfdgs
    username: wptvtfajldujgq
    password: 3897c9bcfb553a9b6a8ac4348ba6df4316f86fbe3c3784a311dd5b3bb3d1e750
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
          lob:
            non_contextual_creation: true
          cache:
            use_query_cache: true
            use_second_level_cache: true
            use_structured_entries: true
            use_minimal_puts: true
        temp:
          use_jdbc_metadata_defaults: false
  jackson:
    default-property-inclusion: non_null